timeout: 700
triggers:
  - name: post-merge
    type: git_poller
    params:
      GIT_URL: "https://github.com/zephyrproject-rtos/zephyr.git"
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: sanity-nrf52
        container: zephyrprojectrtos/zephyr-build
        host-tag: zephyr-nrf52
        privileged: true
        params:
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          PLATFORM: nrf52_blenano2
          BROKE_TESTS: |
            tests/kernel/interrupt
        script-repo:
          name: gavel-ci-projects
          path: zephyr/sanity.sh
      - name: sanity-k64f
        container: zephyrprojectrtos/zephyr-build
        host-tag: zephyr-k64f
        privileged: true
        params:
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          PLATFORM: frdm_k64f
          BROKE_TESTS: |
            samples/basic
            samples/subsys/nvs
            samples/subsys/usb/testusb
            tests/kernel/interrupt
        script-repo:
          name: gavel-ci-projects
          path: zephyr/sanity.sh

script-repos:
  gavel-ci-projects:
    clone-url: https://github.com/doanac/gavel-ci-projects
